image: node

cache:
  paths:
    - node_modules/

#before_script:
#  - apt-get update -qq
#  - apt-get install -qq git
#  - "which ssh-agent || ( apt-get install -qq openssh-client )"
#  - eval $(ssh-agent -s)
#  - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d)
#  - mkdir -p ~/.ssh
#  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

before_script:
  - mkdir -p ~/.ssh
  - (echo "$SSH_PRIVATE_KEY" | base64 -d) | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_rsa
  - ssh-keyscan -H '178.170.47.43' >> ~/.ssh/known_hosts

deploy:
  stage: deploy
  environment:
    name: production
    url: issuer.ssi4.defispace.com
  script:
    - bash scripts/deploy.sh
  only:
    - production

deployToStaging:
  stage: deploy
  environment:
    name: staging
    url: issuer.ssi4.defispace.com
  script:
    - bash scripts/deploy.staging.sh
  only:
    - staging
